In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

##  example dataframe

In [2]:
import pandas as pd

In [3]:
data = {
    "NAME" : ["max","john","alice"],
    "AGE" : [23,22,34],
    "COUNTRY" : ["USA","Canada","UK"]
}

In [4]:
df = pd.DataFrame(data)

print(df)

    NAME  AGE COUNTRY
0    max   23     USA
1   john   22  Canada
2  alice   34      UK

In [5]:
new_row = pd.DataFrame([{   
    "NAME" : "bob",
    "AGE" : 23,
    "COUNTRY" : "india"}])

df = pd.concat([df,new_row],ignore_index = True)

print(df)

    NAME  AGE COUNTRY
0    max   23     USA
1   john   22  Canada
2  alice   34      UK
3    bob   23   india

In [6]:
df.loc[df['NAME']=='max','AGE']=24

print(df)

    NAME  AGE COUNTRY
0    max   24     USA
1   john   22  Canada
2  alice   34      UK
3    bob   23   india

## loading a dataframe

In [7]:
df = pd.read_csv('orders.csv') #for csv

# df = pd.read_xlxs('file.xlxs') #for excel
# df = pd.DataFrame('dict') #for dictionary

print(df)

     NAME   AGE COUNTRY  OrderID CustomerName Product     Category  Quantity  \
0     max  23.0     USA      NaN          NaN     NaN          NaN       NaN
1    john  22.0  Canada      NaN          NaN     NaN          NaN       NaN
2   alice  34.0      UK      NaN          NaN     NaN          NaN       NaN
3     bob  23.0   india      NaN          NaN     NaN          NaN       NaN
4     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
5     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
6     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
7     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
8     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
9     NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
10    NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
11    NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0

      Price   OrderDate Shipped Country
0       NaN         NaN     NaN     NaN
1       NaN         NaN     NaN     NaN
2       NaN         NaN     NaN     NaN
3       NaN         NaN     NaN     NaN
4   75000.0  2024-06-07     Yes   India
5   75000.0  2024-06-07     Yes   India
6   75000.0  2024-06-07     Yes   India
7   75000.0  2024-06-07     Yes   India
8   75000.0  2024-06-07     Yes   India
9   75000.0  2024-06-07     Yes   India
10  75000.0  2024-06-07     Yes   India
11  75000.0  2024-06-07     Yes   India

## exploring data frame

In [8]:
df.head()

,NAME,AGE,COUNTRY,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,max,23.0,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,john,22.0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,alice,34.0,UK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bob,23.0,india,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India

In [9]:
df.tail()

,NAME,AGE,COUNTRY,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
7,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India
8,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India
9,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India
10,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India
11,NaN,NaN,NaN,1001.0,Arul,Laptop,Electronics,2.0,75000.0,2024-06-07,Yes,India

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NAME          4 non-null      object
 1   AGE           4 non-null      float64
 2   COUNTRY       4 non-null      object
 3   OrderID       8 non-null      float64
 4   CustomerName  8 non-null      object
 5   Product       8 non-null      object
 6   Category      8 non-null      object
 7   Quantity      8 non-null      float64
 8   Price         8 non-null      float64
 9   OrderDate     8 non-null      object
 10  Shipped       8 non-null      object
 11  Country       8 non-null      object
dtypes: float64(4), object(8)
memory usage: 1.3+ KB

In [10]:
df.describe()

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [11]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=40, step=1)

## Accessing & Filtering Data

#### Basic Access

In [14]:
df['Quantity'].head()  # single columns

0    1
1    2
2    1
3    3
4    2
Name: Quantity, dtype: int64

In [13]:
df[['Quantity','Country']].head() #multiple column

   Quantity    Country
0         1        USA
1         2     Canada
2         1        UAE
3         3  Singapore
4         2     Mexico

In [14]:
df.iloc[0] # First row by position

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [15]:
df.loc[0] #first row by label

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

### Conditional Filtering (Boolean masks)

In [16]:
df[df['Quantity'] >= 4]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [17]:
df[df['Category']=='Electronics'].head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan

In [18]:
df[(df['Quantity'] >= 4) & (df['Country'] == 'Canada')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada

### Advanced Filtering

In [19]:
df[df['CustomerName'].str.startswith('A')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [20]:
df[df['Country'].isin(['USA', 'UK'])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

In [21]:
df[~df['Country'].isin(['Canada'])].head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE

In [49]:
new_row = pd.DataFrame([{
    "OrderID"      : 1001,
    "CustomerName" : "Arul",
    "Product"      : "Laptop",
    "Category"     : "Electronics",
    "Quantity"     : 2,
    "Price"        : 75000,
    "OrderDate"    : "2024-06-07",
    "Shipped"      : "Yes",
    "Country"      : "India"
}])

df = pd.concat([df,new_row], ignore_index = True)

df.to_csv("orders.csv", index=False)

print(df.tail())

   NAME  AGE COUNTRY  OrderID CustomerName Product     Category  Quantity  \
7   NaN  NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
8   NaN  NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
9   NaN  NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
10  NaN  NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0
11  NaN  NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0

      Price   OrderDate Shipped Country
7   75000.0  2024-06-07     Yes   India
8   75000.0  2024-06-07     Yes   India
9   75000.0  2024-06-07     Yes   India
10  75000.0  2024-06-07     Yes   India
11  75000.0  2024-06-07     Yes   India

In [50]:
df.loc[df['NAME'] == 'Arul']
# df.iloc[3]

Empty DataFrame
Columns: [NAME, AGE, COUNTRY, OrderID, CustomerName, Product, Category, Quantity, Price, OrderDate, Shipped, Country]
Index: []

In [52]:
df.loc[df['CustomerName']=='John Smith','Country']='india'

print(df.head(5))

    NAME   AGE COUNTRY  OrderID CustomerName Product     Category  Quantity  \
0    max  23.0     USA      NaN          NaN     NaN          NaN       NaN
1   john  22.0  Canada      NaN          NaN     NaN          NaN       NaN
2  alice  34.0      UK      NaN          NaN     NaN          NaN       NaN
3    bob  23.0   india      NaN          NaN     NaN          NaN       NaN
4    NaN   NaN     NaN   1001.0         Arul  Laptop  Electronics       2.0

     Price   OrderDate Shipped Country
0      NaN         NaN     NaN     NaN
1      NaN         NaN     NaN     NaN
2      NaN         NaN     NaN     NaN
3      NaN         NaN     NaN     NaN
4  75000.0  2024-06-07     Yes   India

In [11]:
df.iloc[2]

NAME            alice
AGE              34.0
COUNTRY            UK
OrderID           NaN
CustomerName      NaN
Product           NaN
Category          NaN
Quantity          NaN
Price             NaN
OrderDate         NaN
Shipped           NaN
Country           NaN
Name: 2, dtype: object