In [34]:
import pandas as pd

df= pd.read_csv('business_analysis_dataset.csv')

In [35]:
print(df)

     order_id  order_date region     category  quantity     sales      cost  \
0           1  2025-04-05  North  Electronics         2   1738.03   1036.32
1           2  2025-04-08  North    Furniture        10  21385.13  10915.59
2           3  2025-05-26  North    Furniture         9  21266.23  13976.66
3           4  2025-06-04  North         Food         7  17342.40   9614.94
4           5  2025-05-26  North         Food         2  18269.48  11334.10
..        ...         ...    ...          ...       ...       ...       ...
197       198  2025-11-14   East  Electronics        10  21749.57  13953.39
198       199  2025-10-15   East  Electronics         7   1532.40    940.39
199       200  2025-10-13  North         Food         7  42301.98  24753.46
200       201        1990  south         food         8  43157.34  30412.87
201       201        1990  south         food         8  43157.34  30412.87

       profit
0      701.71
1    10469.54
2     7289.57
3     7727.46
4     6935.38
..        ...
197   7796.18
198    592.01
199  17548.52
200   6154.88
201   6154.88

[202 rows x 8 columns]

In [36]:
df.head()

,order_id,order_date,region,category,quantity,sales,cost,profit
0,1,2025-04-05,North,Electronics,2,1738.03,1036.32,701.71
1,2,2025-04-08,North,Furniture,10,21385.13,10915.59,10469.54
2,3,2025-05-26,North,Furniture,9,21266.23,13976.66,7289.57
3,4,2025-06-04,North,Food,7,17342.40,9614.94,7727.46
4,5,2025-05-26,North,Food,2,18269.48,11334.10,6935.38

In [37]:
df.tail()

,order_id,order_date,region,category,quantity,sales,cost,profit
197,198,2025-11-14,East,Electronics,10,21749.57,13953.39,7796.18
198,199,2025-10-15,East,Electronics,7,1532.40,940.39,592.01
199,200,2025-10-13,North,Food,7,42301.98,24753.46,17548.52
200,201,1990,south,food,8,43157.34,30412.87,6154.88
201,201,1990,south,food,8,43157.34,30412.87,6154.88

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    202 non-null    int64
 1   order_date  202 non-null    object
 2   region      202 non-null    object
 3   category    202 non-null    object
 4   quantity    202 non-null    int64
 5   sales       202 non-null    float64
 6   cost        202 non-null    float64
 7   profit      202 non-null    float64
dtypes: float64(3), int64(2), object(3)
memory usage: 12.8+ KB

In [39]:
df.describe()

         order_id    quantity         sales          cost        profit
count  202.000000  202.000000    202.000000    202.000000    202.000000
mean   101.495050    5.519802  25400.696733  17129.789703   8205.663564
std     58.448025    2.984555  14840.608233  10417.621751   5725.422620
min      1.000000    1.000000    675.510000    520.070000    155.440000
25%     51.250000    3.000000  11990.190000   7520.460000   3835.445000
50%    101.500000    6.000000  25268.260000  16652.570000   7266.975000
75%    151.750000    8.000000  40067.670000  25643.252500  12076.035000
max    201.000000   10.000000  49968.990000  40298.080000  22519.420000

In [40]:
df.columns

Index(['order_id', 'order_date', 'region', 'category', 'quantity', 'sales',
       'cost', 'profit'],
      dtype='object')

In [41]:
df.index

RangeIndex(start=0, stop=202, step=1)

In [42]:
df['category'].head()

0    Electronics
1      Furniture
2      Furniture
3           Food
4           Food
Name: category, dtype: object

In [43]:
df[['category','quantity']]

        category  quantity
0    Electronics         2
1      Furniture        10
2      Furniture         9
3           Food         7
4           Food         2
..           ...       ...
197  Electronics        10
198  Electronics         7
199         Food         7
200         food         8
201         food         8

[202 rows x 2 columns]

In [44]:
df.iloc[3]

order_id               4
order_date    2025-06-04
region             North
category            Food
quantity               7
sales            17342.4
cost             9614.94
profit           7727.46
Name: 3, dtype: object

In [45]:
df.loc[20]

order_id              21
order_date    2025-01-20
region              East
category            Food
quantity               9
sales           47698.24
cost            39248.59
profit           8449.65
Name: 20, dtype: object

In [46]:
df[df['quantity'] >= 9]

,order_id,order_date,region,category,quantity,sales,cost,profit
1,2,2025-04-08,North,Furniture,10,21385.13,10915.59,10469.54
2,3,2025-05-26,North,Furniture,9,21266.23,13976.66,7289.57
5,6,2025-02-18,East,Clothing,9,6678.90,5495.42,1183.48
6,7,2025-11-08,East,Electronics,10,10018.29,5253.03,4765.26
9,10,2025-07-09,South,Clothing,9,36591.78,20388.61,16203.17
13,14,2025-07-19,West,Clothing,9,27179.38,20695.87,6483.51
17,18,2025-06-04,East,Food,9,37668.45,28967.40,8701.05
20,21,2025-01-20,East,Food,9,47698.24,39248.59,8449.65
22,23,2025-08-27,North,Furniture,10,47374.00,25107.21,22266.79
24,25,2025-12-10,West,Clothing,9,37885.63,28090.44,9795.19
32,33,2025-05-15,South,Electronics,9,22706.37,14705.98,8000.39
40,41,2025-07-22,East,Clothing,10,29928.70,21452.40,8476.30
45,46,2025-03-09,North,Electronics,9,15319.25,11216.54,4102.71
46,47,2025-04-23,East,Furniture,9,8194.67,4905.45,3289.22
49,50,2025-02-03,South,Electronics,9,35430.54,24670.90,10759.64
52,53,2025-10-24,South,Furniture,9,44264.67,28428.19,15836.48
60,61,2025-07-01,South,Clothing,10,9908.90,5108.39,4800.51
72,73,2025-07-27,West,Furniture,10,40842.82,33172.83,7669.99
75,76,2025-07-23,South,Furniture,9,4488.59,2481.25,2007.34
81,82,2025-11-14,South,Food,10,28437.40,14488.45,13948.95
90,91,2025-10-26,North,Clothing,10,40373.63,31438.12,8935.51
91,92,2025-09-21,East,Electronics,9,21704.71,13667.45,8037.26
101,102,2025-05-10,East,Furniture,9,16874.17,12588.12,4286.05
108,109,2025-03-26,East,Electronics,10,31657.56,16422.78,15234.78
111,112,2025-04-21,South,Clothing,10,48025.38,25680.70,22344.68
120,121,2025-08-17,West,Clothing,10,2491.47,1905.21,586.26
128,129,2025-04-27,North,Food,9,1176.89,756.50,420.39
131,132,2025-02-09,West,Clothing,10,25657.92,20725.55,4932.37
132,133,2025-12-10,West,Furniture,9,13725.05,6874.85,6850.20
140,141,2025-05-08,North,Food,10,3886.83,2802.04,1084.79
145,146,2025-05-15,East,Electronics,10,7584.33,5016.29,2568.04
147,148,2025-12-09,West,Clothing,10,15308.14,12808.48,2499.66
149,150,2025-01-27,West,Clothing,10,15145.68,11279.71,3865.97
153,154,2025-05-11,West,Furniture,10,18560.63,10134.00,8426.63
168,169,2025-04-11,South,Electronics,9,10754.29,6189.99,4564.30
173,174,2025-11-17,East,Food,10,2646.57,2048.79,597.78
181,182,2025-09-11,North,Food,9,3469.06,2896.04,573.02
183,184,2025-09-07,South,Food,10,15966.22,8562.05,7404.17
185,186,2025-09-25,North,Clothing,10,11694.88,7603.89,4090.99
197,198,2025-11-14,East,Electronics,10,21749.57,13953.39,7796.18

In [47]:
df[df['region'] == 'West'].head(10)

,order_id,order_date,region,category,quantity,sales,cost,profit
13,14,2025-07-19,West,Clothing,9,27179.38,20695.87,6483.51
23,24,2025-03-09,West,Furniture,3,33157.67,27567.19,5590.48
24,25,2025-12-10,West,Clothing,9,37885.63,28090.44,9795.19
28,29,2025-10-19,West,Furniture,8,11104.72,6066.61,5038.11
29,30,2025-02-22,West,Clothing,8,40471.10,22932.68,17538.42
34,35,2025-04-28,West,Electronics,4,8732.40,5850.48,2881.92
35,36,2025-05-26,West,Clothing,3,19259.17,16271.27,2987.90
36,37,2025-09-22,West,Furniture,7,34981.28,26434.54,8546.74
42,43,2025-02-01,West,Electronics,8,16150.77,12325.50,3825.27
47,48,2025-01-03,West,Clothing,5,25517.75,15001.69,10516.06

In [48]:
df[(df['quantity'] >= 9) & (df['region'] == 'West')]

,order_id,order_date,region,category,quantity,sales,cost,profit
13,14,2025-07-19,West,Clothing,9,27179.38,20695.87,6483.51
24,25,2025-12-10,West,Clothing,9,37885.63,28090.44,9795.19
72,73,2025-07-27,West,Furniture,10,40842.82,33172.83,7669.99
120,121,2025-08-17,West,Clothing,10,2491.47,1905.21,586.26
131,132,2025-02-09,West,Clothing,10,25657.92,20725.55,4932.37
132,133,2025-12-10,West,Furniture,9,13725.05,6874.85,6850.20
147,148,2025-12-09,West,Clothing,10,15308.14,12808.48,2499.66
149,150,2025-01-27,West,Clothing,10,15145.68,11279.71,3865.97
153,154,2025-05-11,West,Furniture,10,18560.63,10134.00,8426.63

In [49]:
df[df['region'].isin(['West','East'])]

,order_id,order_date,region,category,quantity,sales,cost,profit
5,6,2025-02-18,East,Clothing,9,6678.90,5495.42,1183.48
6,7,2025-11-08,East,Electronics,10,10018.29,5253.03,4765.26
7,8,2025-08-21,East,Furniture,4,43390.94,27468.38,15922.56
10,11,2025-06-13,East,Electronics,1,11837.88,6051.94,5785.94
13,14,2025-07-19,West,Clothing,9,27179.38,20695.87,6483.51
...,...,...,...,...,...,...,...,...
193,194,2025-01-07,East,Furniture,4,20065.54,14241.79,5823.75
194,195,2025-02-01,West,Food,3,38325.96,23045.65,15280.31
195,196,2025-04-17,East,Electronics,3,6894.69,4732.54,2162.15
197,198,2025-11-14,East,Electronics,10,21749.57,13953.39,7796.18
198,199,2025-10-15,East,Electronics,7,1532.40,940.39,592.01

In [50]:
df[~df['region'].isin(['West','East'])]

,order_id,order_date,region,category,quantity,sales,cost,profit
0,1,2025-04-05,North,Electronics,2,1738.03,1036.32,701.71
1,2,2025-04-08,North,Furniture,10,21385.13,10915.59,10469.54
2,3,2025-05-26,North,Furniture,9,21266.23,13976.66,7289.57
3,4,2025-06-04,North,Food,7,17342.40,9614.94,7727.46
4,5,2025-05-26,North,Food,2,18269.48,11334.10,6935.38
...,...,...,...,...,...,...,...,...
191,192,2025-05-07,North,Clothing,7,24540.25,16066.88,8473.37
196,197,2025-01-15,North,Clothing,7,43157.34,22217.65,20939.69
199,200,2025-10-13,North,Food,7,42301.98,24753.46,17548.52
200,201,1990,south,food,8,43157.34,30412.87,6154.88
201,201,1990,south,food,8,43157.34,30412.87,6154.88

In [51]:
new_row = pd.DataFrame([{
    "order_id" : 201,
    "order_date" : 2025-11-24,
    "region" : "south",
    "category" : "food",
    "quantity" : 8,
    "sales" : 43157.34,
    "cost" : 30412.87,
    "profit" : 6154.88
}])

df = pd.concat([df,new_row],ignore_index = True)

df.to_csv("business_analysis_dataset.csv",index = False)

print(df.tail(1))

     order_id order_date region category  quantity     sales      cost  \
202       201       1990  south     food         8  43157.34  30412.87

      profit
202  6154.88

In [55]:
df[df['quantity'] >= 9]

,order_id,order_date,region,category,quantity,sales,cost,profit
1,2,2025-04-08,North,Furniture,10,21385.13,10915.59,10469.54
2,3,2025-05-26,North,Furniture,9,21266.23,13976.66,7289.57
5,6,2025-02-18,East,Clothing,9,6678.90,5495.42,1183.48
6,7,2025-11-08,East,Electronics,10,10018.29,5253.03,4765.26
9,10,2025-07-09,South,Clothing,9,36591.78,20388.61,16203.17
13,14,2025-07-19,West,Clothing,9,27179.38,20695.87,6483.51
17,18,2025-06-04,East,Food,9,37668.45,28967.40,8701.05
20,21,2025-01-20,East,Food,9,47698.24,39248.59,8449.65
22,23,2025-08-27,North,Furniture,10,47374.00,25107.21,22266.79
24,25,2025-12-10,West,Clothing,9,37885.63,28090.44,9795.19
32,33,2025-05-15,South,Electronics,9,22706.37,14705.98,8000.39
40,41,2025-07-22,East,Clothing,10,29928.70,21452.40,8476.30
45,46,2025-03-09,North,Electronics,9,15319.25,11216.54,4102.71
46,47,2025-04-23,East,Furniture,9,8194.67,4905.45,3289.22
49,50,2025-02-03,South,Electronics,9,35430.54,24670.90,10759.64
52,53,2025-10-24,South,Furniture,9,44264.67,28428.19,15836.48
60,61,2025-07-01,South,Clothing,10,9908.90,5108.39,4800.51
72,73,2025-07-27,West,Furniture,10,40842.82,33172.83,7669.99
75,76,2025-07-23,South,Furniture,9,4488.59,2481.25,2007.34
81,82,2025-11-14,South,Food,10,28437.40,14488.45,13948.95
90,91,2025-10-26,North,Clothing,10,40373.63,31438.12,8935.51
91,92,2025-09-21,East,Electronics,9,21704.71,13667.45,8037.26
101,102,2025-05-10,East,Furniture,9,16874.17,12588.12,4286.05
108,109,2025-03-26,East,Electronics,10,31657.56,16422.78,15234.78
111,112,2025-04-21,South,Clothing,10,48025.38,25680.70,22344.68
120,121,2025-08-17,West,Clothing,10,2491.47,1905.21,586.26
128,129,2025-04-27,North,Food,9,1176.89,756.50,420.39
131,132,2025-02-09,West,Clothing,10,25657.92,20725.55,4932.37
132,133,2025-12-10,West,Furniture,9,13725.05,6874.85,6850.20
140,141,2025-05-08,North,Food,10,3886.83,2802.04,1084.79
145,146,2025-05-15,East,Electronics,10,7584.33,5016.29,2568.04
147,148,2025-12-09,West,Clothing,10,15308.14,12808.48,2499.66
149,150,2025-01-27,West,Clothing,10,15145.68,11279.71,3865.97
153,154,2025-05-11,West,Furniture,10,18560.63,10134.00,8426.63
168,169,2025-04-11,South,Electronics,9,10754.29,6189.99,4564.30
173,174,2025-11-17,East,Food,10,2646.57,2048.79,597.78
181,182,2025-09-11,North,Food,9,3469.06,2896.04,573.02
183,184,2025-09-07,South,Food,10,15966.22,8562.05,7404.17
185,186,2025-09-25,North,Clothing,10,11694.88,7603.89,4090.99
197,198,2025-11-14,East,Electronics,10,21749.57,13953.39,7796.18

In [53]:
df.iloc[2]

order_id               3
order_date    2025-05-26
region             North
category       Furniture
quantity               9
sales           21266.23
cost            13976.66
profit           7289.57
Name: 2, dtype: object

In [54]:
df.head()

,order_id,order_date,region,category,quantity,sales,cost,profit
0,1,2025-04-05,North,Electronics,2,1738.03,1036.32,701.71
1,2,2025-04-08,North,Furniture,10,21385.13,10915.59,10469.54
2,3,2025-05-26,North,Furniture,9,21266.23,13976.66,7289.57
3,4,2025-06-04,North,Food,7,17342.40,9614.94,7727.46
4,5,2025-05-26,North,Food,2,18269.48,11334.10,6935.38