In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd

student = {
    "name" : ["alice","bob"],
    "age"  : [20,21],
    "course" : ["AIDS","CSE"]
}

In [13]:
ad = pd.DataFrame(student)
print(ad)

    name  age course
0  alice   20   AIDS
1    bob   21    CSE

#### loading a dataset

In [69]:
df = pd.read_csv('retail_sales_dataset.csv')
df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,Coimbatore
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,Madurai
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,Salem
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,Trichy
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,Erode
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,Vellore
8,2009,Suresh,Mouse,Accessories,5,700,2025-01-24,Tirunelveli
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [70]:
df.head()

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,Coimbatore
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,Madurai
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,Salem
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,Trichy

In [71]:
df.tail()

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SaleID        15 non-null     int64
 1   CustomerName  15 non-null     object
 2   Product       15 non-null     object
 3   Category      15 non-null     object
 4   Quantity      15 non-null     int64
 5   UnitPrice     15 non-null     int64
 6   SaleDate      15 non-null     object
 7   City          15 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.1+ KB

In [73]:
df.describe()

            SaleID   Quantity    UnitPrice
count    15.000000  15.000000     15.00000
mean   1607.133333   2.400000  16360.00000
std     826.600773   1.242118  14078.69718
min      10.000000   1.000000    700.00000
25%    2001.500000   1.000000   5500.00000
50%    2005.000000   3.000000  18000.00000
75%    2008.500000   3.000000  23000.00000
max    2011.000000   5.000000  55000.00000

In [74]:
df.columns

Index(['SaleID', 'CustomerName', 'Product', 'Category', 'Quantity',
       'UnitPrice', 'SaleDate', 'City'],
      dtype='object')

In [75]:
df.index

RangeIndex(start=0, stop=15, step=1)

####  Accessing & Filtering Data

In [76]:
df['CustomerName']

0        Arun
1       Priya
2     Karthik
3       Divya
4       Vijay
5         Anu
6       Rahul
7       Meena
8      Suresh
9     Keerthi
10        joe
11        joe
12        joe
13        joe
14        joe
Name: CustomerName, dtype: object

In [77]:
df[['CustomerName','Product','Category']]

   CustomerName      Product     Category
0          Arun       Laptop  Electronics
1         Priya       Mobile  Electronics
2       Karthik   Headphones  Accessories
3         Divya        Chair    Furniture
4         Vijay         Desk    Furniture
5           Anu  Smart Watch  Electronics
6         Rahul     Keyboard  Accessories
7         Meena      Monitor  Electronics
8        Suresh        Mouse  Accessories
9       Keerthi       Tablet  Electronics
10          joe        Mouse  Accessories
11          joe        Mouse  Accessories
12          joe        Mouse  Accessories
13          joe        Mouse  Accessories
14          joe        Mouse  Accessories

In [78]:
df.iloc[2]

SaleID                 2003
CustomerName        Karthik
Product          Headphones
Category        Accessories
Quantity                  3
UnitPrice              1500
SaleDate         2025-01-14
City                Madurai
Name: 2, dtype: object

In [79]:
df.loc[1]

SaleID                 2002
CustomerName          Priya
Product              Mobile
Category        Electronics
Quantity                  2
UnitPrice             18000
SaleDate         2025-01-12
City             Coimbatore
Name: 1, dtype: object

####    Conditional Filtering (Boolean masks)

In [80]:
df[df['UnitPrice'] >= 12000]

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,Coimbatore
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,Vellore
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [81]:
df[df['City'] == 'Chennai']

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [82]:
df[(df['UnitPrice'] >= 12000) & (df['City'] == 'Chennai')]

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

####    Advanced Filtering

In [83]:
df[df['CustomerName'].str.startswith('A')]

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai

In [84]:
df[df['Product'].isin(['Laptop','Smart Watch','Monitor'])]

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,Vellore

In [85]:
df[~df['Product'].isin(['Monitor'])]

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,Coimbatore
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,Madurai
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,Salem
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,Trichy
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,Erode
8,2009,Suresh,Mouse,Accessories,5,700,2025-01-24,Tirunelveli
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

#   CRUD Operations in Pandas

#### create(insert row)

In [86]:
new_row = pd.DataFrame([{
    	'SaleID' : '10',
        'CustomerName' : 'joe',
        'Product' : 'Mouse',
        'Category' : 'Accessories',
        'Quantity' : 3,
        'UnitPrice' : 23000,
        'SaleDate' : '2025-01-22',
        'City': 'Chennai'
}])

df = pd.concat([df,new_row],ignore_index = True)

df.to_csv('retail_sales_dataset.csv',index = False)

df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,Chennai
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,Coimbatore
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,Madurai
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,Salem
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,Trichy
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,Chennai
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,Erode
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,Vellore
8,2009,Suresh,Mouse,Accessories,5,700,2025-01-24,Tirunelveli
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,Chennai
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
15,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

####  Read (Access Data)

In [87]:
df.loc[df['CustomerName'] == 'joe']

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
15,10,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [88]:
df.iloc[10]

SaleID                 2011
CustomerName            joe
Product               Mouse
Category        Accessories
Quantity                  3
UnitPrice             23000
SaleDate         2025-01-22
City                Chennai
Name: 10, dtype: object

####  Update (Modify Values)

In [89]:
df.loc[df['CustomerName'] == 'joe','SaleID'] = 2011

df.tail()

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
12,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
13,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
14,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai
15,2011,joe,Mouse,Accessories,3,23000,2025-01-22,Chennai

In [90]:
df['City'] = df['City'].str.upper()

df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,CHENNAI
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,COIMBATORE
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,MADURAI
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,SALEM
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,TRICHY
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,CHENNAI
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,ERODE
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,VELLORE
8,2009,Suresh,Mouse,Accessories,5,700,2025-01-24,TIRUNELVELI
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,CHENNAI
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI
11,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI
12,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI
13,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI
14,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI
15,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI

In [91]:
df.duplicated().sum()

np.int64(5)

In [92]:
df = df.drop_duplicates()
df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,CHENNAI
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,COIMBATORE
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,MADURAI
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,SALEM
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,TRICHY
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,CHENNAI
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,ERODE
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,VELLORE
8,2009,Suresh,Mouse,Accessories,5,700,2025-01-24,TIRUNELVELI
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,CHENNAI
10,2011,joe,Mouse,Accessories,3,23000,2025-01-22,CHENNAI

####  Delete (Drop Data)

In [97]:
df = df.drop(8,axis=0)

df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate,City
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10,CHENNAI
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12,COIMBATORE
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14,MADURAI
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15,SALEM
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16,TRICHY
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18,CHENNAI
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20,ERODE
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22,VELLORE
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25,CHENNAI

In [108]:
df = df.drop('City', axis=1,errors='ignore')   

df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25

In [109]:
df.isnull().sum()

SaleID          0
CustomerName    0
Product         0
Category        0
Quantity        0
UnitPrice       0
SaleDate        0
dtype: int64

In [110]:
df.dropna(inplace = True)

In [113]:
df.fillna({'Quantity' : 0},inplace = True)

In [114]:
df

,SaleID,CustomerName,Product,Category,Quantity,UnitPrice,SaleDate
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25

In [115]:
df.rename(columns={'Quantity': 'aalavu'}, inplace=True)

In [116]:
df

  SaleID CustomerName      Product     Category  aalavu  UnitPrice    SaleDate
0   2001         Arun       Laptop  Electronics       1      55000  2025-01-10
1   2002        Priya       Mobile  Electronics       2      18000  2025-01-12
2   2003      Karthik   Headphones  Accessories       3       1500  2025-01-14
3   2004        Divya        Chair    Furniture       1       4500  2025-01-15
4   2005        Vijay         Desk    Furniture       1       7000  2025-01-16
5   2006          Anu  Smart Watch  Electronics       2       6500  2025-01-18
6   2007        Rahul     Keyboard  Accessories       4       1200  2025-01-20
7   2008        Meena      Monitor  Electronics       1      14000  2025-01-22
9   2010      Keerthi       Tablet  Electronics       1      22000  2025-01-25

In [118]:
df['SaleID'] = df['SaleID'].astype(int)

In [119]:
df

,SaleID,CustomerName,Product,Category,aalavu,UnitPrice,SaleDate
0,2001,Arun,Laptop,Electronics,1,55000,2025-01-10
1,2002,Priya,Mobile,Electronics,2,18000,2025-01-12
2,2003,Karthik,Headphones,Accessories,3,1500,2025-01-14
3,2004,Divya,Chair,Furniture,1,4500,2025-01-15
4,2005,Vijay,Desk,Furniture,1,7000,2025-01-16
5,2006,Anu,Smart Watch,Electronics,2,6500,2025-01-18
6,2007,Rahul,Keyboard,Accessories,4,1200,2025-01-20
7,2008,Meena,Monitor,Electronics,1,14000,2025-01-22
9,2010,Keerthi,Tablet,Electronics,1,22000,2025-01-25

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SaleID        9 non-null      int64
 1   CustomerName  9 non-null      object
 2   Product       9 non-null      object
 3   Category      9 non-null      object
 4   aalavu        9 non-null      int64
 5   UnitPrice     9 non-null      int64
 6   SaleDate      9 non-null      object
dtypes: int64(3), object(4)
memory usage: 876.0+ bytes